# Setup
title:        
tagline:     "Poissonsinger: Singing Voice Synthesis with Poisson Flow Model"
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
# markdown: README.md

